### ISSUE TITLE
Asserting while deploying a new system

### ISSUE THREAD

**Issue by votdev** [aquarist-labs/aquarium#599]
Using the Vagrant box image `project-aquarium.main-20210624.241d701.vagrant.libvirt.box` the deployment aborts with the following exception:
```
INFO:     2021-06-29 14:26:07 -- h11_impl -- 192.168.121.100:46734 - "GET /api/nodes/deployment/status HTTP/1.1" 200
INFO:     2021-06-29 14:26:07 -- h11_impl -- 192.168.121.100:46734 - "GET /api/nodes/deployment/status HTTP/1.1" 200
DEBUG:    2021-06-29 14:26:08 -- orchestrator -- devices ls: [OrchDevicesPerHostModel(addr='node01', devices=[], labels=[], name='node01')]
ERROR:    2021-06-29 14:26:08 -- deployment -- unable to assimilate devices
ERROR:    2021-06-29 14:26:08 -- deployment -- 
Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 565, in _assimilate_devices
    while not orch.devices_assimilated(hostname, devices):
  File "/srv/aquarium/src/./gravel/controllers/orch/orchestrator.py", line 98, in devices_assimilated
    assert dev in hostdevs
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 482, in finish_bootstrap_cb
    await _assimilate_devices()
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 501, in _assimilate_devices
    await self._assimilate_devices(hostname, devices)
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 569, in _assimilate_devices
    raise DeploymentError(str(e))
gravel.controllers.nodes.deployment.DeploymentError
ERROR:    2021-06-29 14:26:08 -- base_events -- Task exception was never retrieved
future: <Task finished name='Task-768' coro=<Bootstrap._do_bootstrap() done, defined at /srv/aquarium/src/./gravel/controllers/nodes/bootstrap.py:85> exception=AssertionError()>
Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 565, in _assimilate_devices
    while not orch.devices_assimilated(hostname, devices):
  File "/srv/aquarium/src/./gravel/controllers/orch/orchestrator.py", line 98, in devices_assimilated
    assert dev in hostdevs
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 482, in finish_bootstrap_cb
    await _assimilate_devices()
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 501, in _assimilate_devices
    await self._assimilate_devices(hostname, devices)
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 569, in _assimilate_devices
    raise DeploymentError(str(e))
gravel.controllers.nodes.deployment.DeploymentError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/aquarium/src/./gravel/controllers/nodes/bootstrap.py", line 116, in _do_bootstrap
    await cb(True, None)
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 490, in finish_bootstrap_cb
    await finisher(False, e.message)
  File "/srv/aquarium/src/./gravel/controllers/nodes/mgr.py", line 455, in _finish_deployment
    self._deployment.finish_deployment()
  File "/srv/aquarium/src/./gravel/controllers/nodes/deployment.py", line 533, in finish_deployment
    assert self.state.bootstrapping
AssertionError
DEBUG:    2021-06-29 14:26:08 -- gstate -- tick devices
```

**Comment by jecluis** [comment]
This has been fixed in latest main.
